In [1]:
# Re-import modified modules without restarting the server
%load_ext autoreload
%autoreload 2

In [3]:
import os
import sys
import warnings

notebook_path = os.path.abspath(get_ipython().starting_dir)
parent_path = os.path.dirname(notebook_path)

sys.path.append(parent_path)
warnings.simplefilter("ignore")

In [4]:
from attribution.api_attribution import OpenAIAttributor
from attribution.experiment_logger import ExperimentLogger
from attribution.token_perturbation import (
    FixedPerturbationStrategy,
    NthNearestPerturbationStrategy,
)

In [5]:
attributor = OpenAIAttributor()
logger = ExperimentLogger()
attributor.compute_attributions(
    "The clock shows 9:47 PM. How many minutes 'til 10?",
    perturbation_strategy=NthNearestPerturbationStrategy(n=-1),
    attribution_strategies=["cosine"],
    logger=logger,
    perturb_word_wise=True,
)
display(logger.df_experiments)
logger.print_sentence_attribution()
logger.print_attribution_matrix(exp_id=1)

,exp_id,original_input,original_output,perturbation_strategy,perturb_word_wise,duration
0,1,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,9.234131

Attribution matrix for experiment 1
Attribution Strategy: cosine
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

In [7]:
logger.print_attribution_matrix(exp_id=1, show_debug_cols=True)

Attribution matrix for experiment 1
Attribution Strategy: cosine
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

In [74]:
attributor = OpenAIAttributor()

input_texts = ["The clock shows 9:47 PM. How many minutes 'til 10?"]

perturbation_strategies = [
    FixedPerturbationStrategy(),
    NthNearestPerturbationStrategy(n=0),
    NthNearestPerturbationStrategy(n=-1),
    # (PerturbationStrategy.NTH_NEAREST, {"n": 10}),
]

# Initialize the logger
logger = ExperimentLogger()

# Perform the experiment
for input_text in input_texts:
    for perturbation_strategy in perturbation_strategies:
        attributor.compute_attributions(
            input_text,
            perturbation_strategy=perturbation_strategy,
            attribution_strategies=["cosine", "prob_diff", "token_displacement"],
            logger=logger,
            perturb_word_wise=True,
        )

# Display the results
display(logger.df_experiments)
logger.print_sentence_attribution()

replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens
replacement_tokens  The
replacement_tokens  clock
replacement_tokens  shows
replacement_tokens  9:47
replacement_tokens  PM.
replacement_tokens  How
replacement_tokens  many
replacement_tokens  minutes
replacement_tokens  'til
replacement_tokens  10?

In [ ]:
logger.print_attribution_matrix(exp_id=1, show_debug_cols=True)

Attribution matrix for experiment 1
Attribution Strategy: cosine
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

Attribution matrix for experiment 1
Attribution Strategy: prob_diff
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

Attribution matrix for experiment 1
Attribution Strategy: token_displacement
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

In [18]:
logger.print_attribution_matrix(exp_id=11)

Attribution matrix for experiment 11
Attribution Strategy: cosine
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

Attribution matrix for experiment 11
Attribution Strategy: prob_diff
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

Attribution matrix for experiment 11
Attribution Strategy: token_displacement
Perturbation strategy: nth_nearest (n=-1):
Input Tokens (Rows) vs. Output Tokens (Columns)

In [17]:
logger.df_experiments

,exp_id,original_input,original_output,perturbation_strategy,perturb_word_wise,duration
0,1,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,11.886951
1,2,The clock shows 9:47 PM. How many minutes 'til...,There are 13 minutes until 10:00 PM.,nth_nearest (n=-1),True,None
2,3,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,None
3,4,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,None
4,5,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,None
5,6,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,None
6,7,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,None
7,8,The clock shows 9:47 PM. How many minutes 'til...,There are 13 minutes until 10:00 PM.,nth_nearest (n=-1),True,None
8,9,The clock shows 9:47 PM. How many minutes 'til...,There are 13 minutes until 10:00 PM.,nth_nearest (n=-1),True,None
9,10,The clock shows 9:47 PM. How many minutes 'til...,There are 13 minutes until 10:00 PM.,nth_nearest (n=-1),True,None
10,11,The clock shows 9:47 PM. How many minutes 'til...,13 minutes.,nth_nearest (n=-1),True,None